### ISSUE TITLE
Hierarchical parsing, howto ?

### ISSUE THREAD

**Issue by fulup-bzh** [tlsa/libcyaml#144]
I already used libcyaml in a project and I loved it? Nevertheless today we would now like to use it to parse bigger configuration files. For this we need to parse the config file in phases and not in one shot. The reason is that we have a config for the main program and multiple custom config schema attached to each plugins that are loaded dynamically after config file is parsed. As a result on lone hand we cannot known the schema of a given plugin before this one is loaded. On the other hand we do not have the list of plugin before we started to load the main config.

As a result I wonder if it is possible to load a sub YAML attached to a specific key without parsing it and retrieve this YAML-subset as a simple string. Then when a plugin is loaded we could pass the unprocessed YAML-subset to the custom plugin we just loaded to be parsed. 

As example in following pseudo YAML plugin1 & 2 may not have the same schema config. I would like main to load plugin-1 config as a string and pass it to the plugin when loaded.

```yaml
main:
  options:
   - opt: xxx
     value: yyy
plugins:
 - name: plugin_1.so
    config:
     (plugin 1 YAML custom schema & config)

  -name: plugin_2.so
   config:
     (plugin 2 YAML custom schema & config)
```

**Comment by tlsa** [comment]
I updated your comment to add YAML styling to the example.

**Comment by fulup-bzh** [comment]
Thank you, it make the issue easier to understand

**Comment by tlsa** [comment]
OK there are a few options I'd suggest here:

## Separate files

You could maybe have the main config list the plugins to load, for example:

```yaml
main:
  options:
   - opt: xxx
     value: yyy
   - plugins:
     - plugin_1.so
     - plugin_2.so
```
And then separate files like for plugin configs:

*plugin_1.so.yaml*:
```yaml
name: plugin_1.so
config:
  (plugin 1 YAML custom schema & config)
```
*plugin_2.so.yaml*:
```yaml
name: plugin_2.so
config:
  (plugin 2 YAML custom schema & config)
```

## Multi-line strings

Note that the correct indentation is very important here:

```yaml
main:
  options:
   - opt: xxx
     value: yyy
plugins:
- name: plugin_1.so
  config: |
    - opt1: xxx
      value: yyy
    - opt2: xxx
      value: yyy

- name: plugin_2.so
  config: |
    - opt1: xxx
      value: yyy
    - opt2: xxx
      value: yyy
```
The `|` character starts a multi-line string that preserves new lines, so you should be able to pass those strings to the plugins, which the plugins could parse themselves.
