### ISSUE TITLE
How to use Anchor and Alias for cyaml

### ISSUE THREAD

**Issue by orassemusse** [tlsa/libcyaml#187]
Hello,
II used Anchors for data settings as follow:
`refs:
  - name: &normalColor
    value: 0xffffffff
  - name: &hoverColor
    value: 0xeeeeeeff
  - name: &activeColor
    value: 0xaaaaaaff
  - name: &focusColor
    value: 0xffffffff
  - name: &textColor
    value: 0xffffffff
  - name: &font
    value: arial.ttf
  - name: &fontSize
    value: 16
  - name: &disabledOpacity
    value: 0.5
`

But I fail getting back the values. For example, logs give:
libcyaml:    INFO: Load: [opacity]
libcyaml:    INFO: Load: Found alias for anchor: 'disabledOpacity'
libcyaml:   DEBUG: Load: Replaying event idx 7: event data: 7
libcyaml:   DEBUG: Load: Finishing handling of alias: 'disabledOpacity'
libcyaml:   DEBUG: Load: Event: SCALAR
libcyaml:   DEBUG: Load: Handle state in mapping (value)
libcyaml:   DEBUG: Load: Reading value of type 'STRING' (pointer)
libcyaml:   DEBUG: Load: Allocation: 0x2819501d0 (0 + 1 bytes)
libcyaml:    INFO: Load:   <>

It might be again how I have written my schema.
Would you please drop an eyes on them and give me hints how to solve this ?

I would also request some more advanced examples than "Fibonacci" sample on how to use properly the API.
Best regards,
Olivier
 
[theme.h.txt](https://github.com/tlsa/libcyaml/files/8831010/theme.h.txt)
[base-theme.yaml.txt](https://github.com/tlsa/libcyaml/files/8831013/base-theme.yaml.txt)

**Comment by tlsa** [comment]
Anchors identify an item in the document and are marked with an `&` character. You then refer to an anchored item using an alias, which is marked by the `*` character.

For example:

```
refs:
  - &normalColor 0xffffffff
  - &hoverColor 0xeeeeeeff
  - &activeColor 0xaaaaaaff
  - &focusColor 0xffffffff
  - &textColor 0xffffffff
skin:
  - name: ButtonSkinHover
    color: *hoverColor
  - name: ButtonSkinActive
    color: *activeColor
  - name: ButtonSkinFocus
    color: *focusColor
```

> I would also request some more advanced examples than "Fibonacci" sample on how to use properly the API.

The [planner](https://github.com/tlsa/libcyaml/tree/main/examples/planner) example has extensive documentation in `main.c`.
