### ISSUE TITLE
How to parse nameless list of map?

### ISSUE THREAD

**Issue by freeze-dolphin** [tlsa/libcyaml#222]
suppose that there's a yaml like this:
```yaml
- name: "Jason"
  age: 23
  gender: male
- name: "Lisa"
  age: 26
  gender: female
- name: "A"
  age: 20
  gender: unknown
```

maybe I can write the schema like this:
```c
enum gender {
    MALE, FEMALE, UNKNOWN
};

struct person {
    const char *name;
    const int age;
    enum gender gdr;
};

static const cyaml_strval_t gender_strings[] = {
        {"male", MALE},
        {"female", FEMALE},
        {"unknown", UNKNOWN},
};

static const cyaml_schema_field_t entry_fields_schema[] = {
        CYAML_FIELD_STRING_PTR(
                "name", CYAML_FLAG_POINTER,
                struct person, name, 0, CYAML_UNLIMITED),
        CYAML_FIELD_UINT(
                "age", CYAML_FLAG_DEFAULT,
                struct person, age),
        CYAML_FIELD_ENUM("gender", CYAML_FLAG_DEFAULT,
                         struct person, gdr, level_type_strings, CYAML_ARRAY_LEN(gender_strings)),
        CYAML_FIELD_END
};

static const cyaml_schema_value_t entry_schema = {
        CYAML_VALUE_MAPPING(CYAML_FLAG_POINTER,
                            struct person, entry_fields_schema),
};
```

But how to actually parse it??
